import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import SideNav from '@/app/ui/home/sidenav';
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<div className="flex h-screen  flex-col md:flex-row md:overflow-hidden">
					<div className="w-full md:w-48 bg-orange-100  md:shadow-2xl max-md:shadow-lg shadow-orange-300  ">
						<SideNav />
					</div>
					<div className="flex-grow p-6 md:overflow-y-auto md:p-12 bg-amber-50">
						{children}
					</div>
				</div>
			</body>
		</html>
	);
}
